-- MySQL Script generated by MySQL Workbench
-- 03/31/15 19:09:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avupdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avupdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avupdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `avupdb` ;

-- -----------------------------------------------------
-- Table `avupdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `profile_name` VARCHAR(25) NULL,
  `date_of_birth` DATE NULL,
  `user_img` LONGTEXT NULL,
  `premium_status` INT NULL,
  `notifications` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`owner` (
  `owner_id` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`owner_id`, `user_user_id`),
  INDEX `fk_owner_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_owner_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `avupdb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`groups` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `owner_owner_id` INT NOT NULL,
  `owner_user_user_id` INT NOT NULL,
  `title` VARCHAR(25) NULL,
  `group_img` LONGTEXT NULL,
  PRIMARY KEY (`group_id`, `owner_owner_id`, `owner_user_user_id`),
  INDEX `fk_group_owner1_idx` (`owner_owner_id` ASC, `owner_user_user_id` ASC),
  CONSTRAINT `fk_group_owner1`
    FOREIGN KEY (`owner_owner_id` , `owner_user_user_id`)
    REFERENCES `avupdb`.`owner` (`owner_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`contacts` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` INT NOT NULL,
  `friends` VARCHAR(45) NULL,
  `datetime` DATETIME NULL,
  `acceptContact` TINYINT(1) NULL,
  PRIMARY KEY (`contact_id`, `user_user_id`),
  INDEX `fk_comments_user_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `avupdb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`user_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`user_has_group` (
  `user_user_id` INT NOT NULL,
  `group_group_id` INT NOT NULL,
  `group_owner_owner_id` INT NOT NULL,
  `group_owner_user_user_id` INT NOT NULL,
  `join_group` TINYINT(1) NULL,
  `accept_user` TINYINT(1) NULL,
  `date_time_au` DATETIME NULL,
  `date_time_jg` DATETIME NULL,
  PRIMARY KEY (`user_user_id`, `group_group_id`, `group_owner_owner_id`, `group_owner_user_user_id`),
  INDEX `fk_user_has_group_group1_idx` (`group_group_id` ASC, `group_owner_owner_id` ASC, `group_owner_user_user_id` ASC),
  INDEX `fk_user_has_group_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_has_group_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `avupdb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_group_group1`
    FOREIGN KEY (`group_group_id` , `group_owner_owner_id` , `group_owner_user_user_id`)
    REFERENCES `avupdb`.`groups` (`group_id` , `owner_owner_id` , `owner_user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`group_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`group_media` (
  `media_id` INT NOT NULL AUTO_INCREMENT,
  `group_group_id` INT NOT NULL,
  `group_owner_owner_id` INT NOT NULL,
  `group_owner_user_user_id` INT NOT NULL,
  `media` LONGTEXT NULL,
  `favorite` TINYINT(1) NULL,
  `upload_time` DATETIME NULL,
  `user_has_group_user_user_id` INT NOT NULL,
  `user_has_group_group_group_id` INT NOT NULL,
  `user_has_group_group_owner_owner_id` INT NOT NULL,
  `user_has_group_group_owner_user_user_id` INT NOT NULL,
  PRIMARY KEY (`media_id`, `group_group_id`, `group_owner_owner_id`, `group_owner_user_user_id`, `user_has_group_user_user_id`, `user_has_group_group_group_id`, `user_has_group_group_owner_owner_id`, `user_has_group_group_owner_user_user_id`),
  INDEX `fk_group_media_group1_idx` (`group_group_id` ASC, `group_owner_owner_id` ASC, `group_owner_user_user_id` ASC),
  INDEX `fk_group_media_user_has_group1_idx` (`user_has_group_user_user_id` ASC, `user_has_group_group_group_id` ASC, `user_has_group_group_owner_owner_id` ASC, `user_has_group_group_owner_user_user_id` ASC),
  CONSTRAINT `fk_group_media_group1`
    FOREIGN KEY (`group_group_id` , `group_owner_owner_id` , `group_owner_user_user_id`)
    REFERENCES `avupdb`.`groups` (`group_id` , `owner_owner_id` , `owner_user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_media_user_has_group1`
    FOREIGN KEY (`user_has_group_user_user_id` , `user_has_group_group_group_id` , `user_has_group_group_owner_owner_id` , `user_has_group_group_owner_user_user_id`)
    REFERENCES `avupdb`.`user_has_group` (`user_user_id` , `group_group_id` , `group_owner_owner_id` , `group_owner_user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`comments` (
  `comments_id` INT NOT NULL AUTO_INCREMENT,
  `group_media_media` INT NOT NULL,
  `group_media_group_group_id` INT NOT NULL,
  `group_media_group_owner_owner_id` INT NOT NULL,
  `group_media_group_owner_user_user_id` INT NOT NULL,
  `comments` VARCHAR(255) NULL,
  `date_time` DATETIME NULL,
  `group_media_media_id` INT NOT NULL,
  `group_media_group_group_id1` INT NOT NULL,
  `group_media_group_owner_owner_id1` INT NOT NULL,
  `group_media_group_owner_user_user_id1` INT NOT NULL,
  `group_media_user_has_group_user_user_id` INT NOT NULL,
  `group_media_user_has_group_group_group_id` INT NOT NULL,
  `group_media_user_has_group_group_owner_owner_id` INT NOT NULL,
  `group_media_user_has_group_group_owner_user_user_id` INT NOT NULL,
  PRIMARY KEY (`comments_id`, `group_media_media`, `group_media_group_group_id`, `group_media_group_owner_owner_id`, `group_media_group_owner_user_user_id`, `group_media_media_id`, `group_media_group_group_id1`, `group_media_group_owner_owner_id1`, `group_media_group_owner_user_user_id1`, `group_media_user_has_group_user_user_id`, `group_media_user_has_group_group_group_id`, `group_media_user_has_group_group_owner_owner_id`, `group_media_user_has_group_group_owner_user_user_id`),
  INDEX `fk_comments_group_media1_idx` (`group_media_media_id` ASC, `group_media_group_group_id1` ASC, `group_media_group_owner_owner_id1` ASC, `group_media_group_owner_user_user_id1` ASC, `group_media_user_has_group_user_user_id` ASC, `group_media_user_has_group_group_group_id` ASC, `group_media_user_has_group_group_owner_owner_id` ASC, `group_media_user_has_group_group_owner_user_user_id` ASC),
  CONSTRAINT `fk_comments_group_media1`
    FOREIGN KEY (`group_media_media_id` , `group_media_group_group_id1` , `group_media_group_owner_owner_id1` , `group_media_group_owner_user_user_id1` , `group_media_user_has_group_user_user_id` , `group_media_user_has_group_group_group_id` , `group_media_user_has_group_group_owner_owner_id` , `group_media_user_has_group_group_owner_user_user_id`)
    REFERENCES `avupdb`.`group_media` (`media_id` , `group_group_id` , `group_owner_owner_id` , `group_owner_user_user_id` , `user_has_group_user_user_id` , `user_has_group_group_group_id` , `user_has_group_group_owner_owner_id` , `user_has_group_group_owner_user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`messaging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`messaging` (
  `messeging_id` INT NOT NULL AUTO_INCREMENT,
  `contacts_user_user_id` INT NOT NULL,
  `contacts_contact_id` INT NOT NULL,
  `media` LONGTEXT NULL,
  `favorite` TINYINT(1) NULL,
  `upload_time` DATETIME NULL,
  `text` VARCHAR(255) NULL,
  `new_message` TINYINT(1) NULL,
  PRIMARY KEY (`messeging_id`, `contacts_user_user_id`, `contacts_contact_id`),
  INDEX `fk_messaging_contacts1_idx` (`contacts_contact_id` ASC, `contacts_user_user_id` ASC),
  CONSTRAINT `fk_messaging_contacts1`
    FOREIGN KEY (`contacts_contact_id` , `contacts_user_user_id`)
    REFERENCES `avupdb`.`contacts` (`contact_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`group_media_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`group_media_note` (
  `group_media_note_id` INT NOT NULL AUTO_INCREMENT,
  `new-media_seen` TINYINT(1) NULL,
  `group_media_media_id` INT NOT NULL,
  `group_media_group_group_id` INT NOT NULL,
  `group_media_group_owner_owner_id` INT NOT NULL,
  `group_media_group_owner_user_user_id` INT NOT NULL,
  `group_media_user_has_group_user_user_id` INT NOT NULL,
  `group_media_user_has_group_group_group_id` INT NOT NULL,
  `group_media_user_has_group_group_owner_owner_id` INT NOT NULL,
  `group_media_user_has_group_group_owner_user_user_id` INT NOT NULL,
  PRIMARY KEY (`group_media_note_id`, `group_media_media_id`, `group_media_group_group_id`, `group_media_group_owner_owner_id`, `group_media_group_owner_user_user_id`, `group_media_user_has_group_user_user_id`, `group_media_user_has_group_group_group_id`, `group_media_user_has_group_group_owner_owner_id`, `group_media_user_has_group_group_owner_user_user_id`),
  INDEX `fk_group_media_note_group_media1_idx` (`group_media_media_id` ASC, `group_media_group_group_id` ASC, `group_media_group_owner_owner_id` ASC, `group_media_group_owner_user_user_id` ASC, `group_media_user_has_group_user_user_id` ASC, `group_media_user_has_group_group_group_id` ASC, `group_media_user_has_group_group_owner_owner_id` ASC, `group_media_user_has_group_group_owner_user_user_id` ASC),
  CONSTRAINT `fk_group_media_note_group_media1`
    FOREIGN KEY (`group_media_media_id` , `group_media_group_group_id` , `group_media_group_owner_owner_id` , `group_media_group_owner_user_user_id` , `group_media_user_has_group_user_user_id` , `group_media_user_has_group_group_group_id` , `group_media_user_has_group_group_owner_owner_id` , `group_media_user_has_group_group_owner_user_user_id`)
    REFERENCES `avupdb`.`group_media` (`media_id` , `group_group_id` , `group_owner_owner_id` , `group_owner_user_user_id` , `user_has_group_user_user_id` , `user_has_group_group_group_id` , `user_has_group_group_owner_owner_id` , `user_has_group_group_owner_user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avupdb`.`comments_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avupdb`.`comments_note` (
  `comments_note_id` INT NOT NULL AUTO_INCREMENT,
  `comments_note_seen` TINYINT(1) NULL,
  `comments_comments_id` INT NOT NULL,
  `comments_group_media_media` INT NOT NULL,
  `comments_group_media_group_group_id` INT NOT NULL,
  `comments_group_media_group_owner_owner_id` INT NOT NULL,
  `comments_group_media_group_owner_user_user_id` INT NOT NULL,
  `comments_group_media_media_id` INT NOT NULL,
  `comments_group_media_group_group_id1` INT NOT NULL,
  `comments_group_media_group_owner_owner_id1` INT NOT NULL,
  `comments_group_media_group_owner_user_user_id1` INT NOT NULL,
  `comments_group_media_user_has_group_user_user_id` INT NOT NULL,
  `comments_group_media_user_has_group_group_group_id` INT NOT NULL,
  `comments_group_media_user_has_group_group_owner_owner_id` INT NOT NULL,
  `comments_group_media_user_has_group_group_owner_user_user_id` INT NOT NULL,
  PRIMARY KEY (`comments_note_id`, `comments_comments_id`, `comments_group_media_media`, `comments_group_media_group_group_id`, `comments_group_media_group_owner_owner_id`, `comments_group_media_group_owner_user_user_id`, `comments_group_media_media_id`, `comments_group_media_group_group_id1`, `comments_group_media_group_owner_owner_id1`, `comments_group_media_group_owner_user_user_id1`, `comments_group_media_user_has_group_user_user_id`, `comments_group_media_user_has_group_group_group_id`, `comments_group_media_user_has_group_group_owner_owner_id`, `comments_group_media_user_has_group_group_owner_user_user_id`),
  INDEX `fk_comments_note_comments1_idx` (`comments_comments_id` ASC, `comments_group_media_media` ASC, `comments_group_media_group_group_id` ASC, `comments_group_media_group_owner_owner_id` ASC, `comments_group_media_group_owner_user_user_id` ASC, `comments_group_media_media_id` ASC, `comments_group_media_group_group_id1` ASC, `comments_group_media_group_owner_owner_id1` ASC, `comments_group_media_group_owner_user_user_id1` ASC, `comments_group_media_user_has_group_user_user_id` ASC, `comments_group_media_user_has_group_group_group_id` ASC, `comments_group_media_user_has_group_group_owner_owner_id` ASC, `comments_group_media_user_has_group_group_owner_user_user_id` ASC),
  CONSTRAINT `fk_comments_note_comments1`
    FOREIGN KEY (`comments_comments_id` , `comments_group_media_media` , `comments_group_media_group_group_id` , `comments_group_media_group_owner_owner_id` , `comments_group_media_group_owner_user_user_id` , `comments_group_media_media_id` , `comments_group_media_group_group_id1` , `comments_group_media_group_owner_owner_id1` , `comments_group_media_group_owner_user_user_id1` , `comments_group_media_user_has_group_user_user_id` , `comments_group_media_user_has_group_group_group_id` , `comments_group_media_user_has_group_group_owner_owner_id` , `comments_group_media_user_has_group_group_owner_user_user_id`)
    REFERENCES `avupdb`.`comments` (`comments_id` , `group_media_media` , `group_media_group_group_id` , `group_media_group_owner_owner_id` , `group_media_group_owner_user_user_id` , `group_media_media_id` , `group_media_group_group_id1` , `group_media_group_owner_owner_id1` , `group_media_group_owner_user_user_id1` , `group_media_user_has_group_user_user_id` , `group_media_user_has_group_group_group_id` , `group_media_user_has_group_group_owner_owner_id` , `group_media_user_has_group_group_owner_user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
